### ISSUE TITLE
[Feature] Add a teleportation delay

### ISSUE THREAD

**Issue by AfkF24** [DarkEyeDragon/RandomTeleport#1]
What the tittle suggests. Series of events would then be:
`initteleport` -> `wait (eg. 3 seconds)` -> `teleport`.

If the player moves during the waiting period, the teleportation would get cancelled.

**Comment by DarkEyeDragon** [comment]
Will add this in a future release.

**Comment by DarkEyeDragon** [comment]
Added in https://github.com/DarkEyeDragon/RandomTeleport/commit/39c5e91cb934f54656fbaa1f7cf1a15b0f1cbd6e
