### ISSUE TITLE
Add support for GriefDefender, please!

### ISSUE THREAD

**Issue by chickenmcjesus** [DarkEyeDragon/RandomTeleport#10]
GriefDefender is a fantastic alternative to GriefPrevention  (found here): https://www.spigotmc.org/resources/griefdefender.68900/

It would be great if this plugin supported not teleporting in GriefDefender claims! Thanks!

**Comment by DarkEyeDragon** [comment]
I'll look into it. If their API allows it i'll add support for it.

**Comment by DarkEyeDragon** [comment]
Could you join our discord? https://discord.gg/NXDk2Q I only have the api to work with so i cant validate if it actually works. I do however think i got a working prototype

**Comment by DarkEyeDragon** [comment]
Added in a1e91de2d7aca891c5a117404ada1f694ec5dfde and will be released in 1.4.2
