### ISSUE TITLE
RandomTeleport 1.14.4

### ISSUE THREAD

**Issue by srrawr11** [DarkEyeDragon/RandomTeleport#107]
Hi, I am using 1.14.4 version and I am using this plugin to TP in worlds..
Basically, when I do /rtp <name of the world> it doesn't tp me..

Just it says in the console.. [15:49:16 INFO]: [RandomTeleport] Safe location consumed for survival (0/5).. and nothing happens..
This is my config..
Link: https://pastebin.com/G8dicXi6

Thanks, will wait for your answer.. keep safe! ^^

**Comment by DarkEyeDragon** [comment]
Can you paste your latest.log aswel?

**Comment by DarkEyeDragon** [comment]
Before you post that could you also reproduce the things you did for it to break? so i can see what's happening in he logs.

**Comment by srrawr11** [comment]
This is the latest log that I got from now: https://pastebin.com/BVEkAXuY

**Comment by DarkEyeDragon** [comment]
It looks like it's not finding any safe locations for some reason. Does it work if you reset the config and leave its default settings (but with the actual world name)?

Reset the config and then change `world` to `survival` under the `worlds` section. I feel like something is messing with the config.
If that doesn't fix it, try the latest build from https://ci.darkeyedragon.me/ if that doesn't fix it, well i'm not sure then tbh.

I don't have very detailed logging in the searcher yet.
Might be easier if you join https://discord.gg/47YEbMm

**Comment by srrawr11** [comment]
I just did what you guide me, I removed the folder and generated a default one, changed the world to survival and then try it again.. this is the log.. https://pastebin.com/B3ur2cyJ

**Comment by DarkEyeDragon** [comment]
Resolved on the discord by upgrading mc version and switching to paper.
