### ISSUE TITLE
Can't RTP in MultiVerse World unless I reload the plugin

### ISSUE THREAD

**Issue by BrainStone** [DarkEyeDragon/RandomTeleport#119]
**Describe the bug**

When trying to RTP in a world added by Multiverse you are being told that you can't do that in the world. Even though the world is not restricted.  
Only reloading the plugin fixes that issue.

**To Reproduce**
1. Add a world with MV
2. Restart the server
3. Go to the world and run `/rtp`

**Expected behavior**
All worlds to work regardless of how they are added

**Minecraft Version**
1.16.5

**Plugin version**
2.0.0.68

**Comment by DarkEyeDragon** [comment]
The reason this happens is that the plugin has no idea the world was created. Hence has no way to generate locations for it.
Hooking into the worldload event should solve that issue.

However i'm in the middle of refactoring some stuff which i need to finish first before i can start adding features again.

**Comment by BrainStone** [comment]
Not correct. It detects the world when it initially fills the queue. But it still somehow caches settings/permissions incorrectly.

**Comment by DarkEyeDragon** [comment]
Fixed on the dev branch. You can test these changes using https://ci.darkeyedragon.me/job/Random%20Teleport/100/ build 100 and up. Note that this branch is not production ready and should be tested properly first.

**Comment by BrainStone** [comment]
Alright. Anything to be weary off when testing?

**Comment by BrainStone** [comment]
I can confirm, world tab completion is broken, but RTP works in the world right away!

I think it can be closed but I'll leave it up to you

**Comment by DarkEyeDragon** [comment]
I'll leave it open until its merged in master so you get a notification for it :)
