### ISSUE TITLE
Support KingdomsX

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [DarkEyeDragon/RandomTeleport#187]
Please add KingdomsX to the list of plugins that are considered when teleporting so that players won't be teleported into that area.

Spigot page: https://www.spigotmc.org/resources/kingdomsx.77670/
Github page: https://github.com/CryptoMorin/KingdomsX/

**Comment by DarkEyeDragon** [comment]
The validator can be found on https://ci.darkeyedragon.me/job/Random%20Teleport%20-%20Addons/
I have not tested it fully so let me know if there are any issues, but it should just work.

Make sure you're using a 2.1.x version of RTP which can be found on https://ci.darkeyedragon.me/job/Random%20Teleport/

Just drop it in the addons folder and should be good to go. If you're using an older version of RTP should let the config regenerate as it does not update automatically. The validator section got removed as it just checks whatever is in the addon folder now.

I'm using kingdoms version 1.11.11 as minimal required version

Closed by https://github.com/DarkEyeDragon/RandomTeleport-Addons/pull/5/commits/b4dbc6a5aff8167e3727b46ece735c9390042ad5
