### ISSUE TITLE
Server uses a lot of ram.

### ISSUE THREAD

**Issue by efinst0rm** [DarkEyeDragon/RandomTeleport#197]
**Describe the bug**
Over time the server will use up all of its ram. Tested this with just this plugin loaded and in a span of 14 hours it eat up all the sever ram.

**To Reproduce**
1. Add plugin wait and few hours 
2. As players join and leave server will eat more and more ram

**Screenshots**
![JmqQW464mAcb0QBOeNYW](https://user-images.githubusercontent.com/7751074/150659381-abac45e2-fa5c-4e66-98a9-5e3afd3033cf.png)

**Minecraft Version**
Paper version git-Paper-169 (MC: 1.18.1) 

**Plugin version**
What version of the plugin are you running?
RandomTeleport version 2.1.0.141

**Comment by DarkEyeDragon** [comment]
Does this happen at all with no plugins? Could just be the server slowly eating RAM. Could you test this just to make sure?
I don't have any logic that deals with players joining and leaving

**Comment by efinst0rm** [comment]
Tested with only the plugin running and in about 8 hours it was 12 GB used. I am guessing the issue is when it uses up the random  locations and has to find new places.

**Comment by DarkEyeDragon** [comment]
Sounds to me like it's just related to the server loading chunks. Which is out of my control. 
Unless you have memory dumps showing my plugin being the culprit here. 

I suggest taking a look to optimize your flags if you haven't already https://blog.airplane.gg/aikar-flags.

Your RAM being used isn't really a bad thing. It only becomes an issue when it's not able to be freed again (memory leak) .

**Comment by efinst0rm** [comment]
@DarkEyeDragon Is there anything else I can do to help you with debugging this? I am using the aikar flags already. I've started restarting my server twice a day now just to prevent it running out of ram.

**Comment by DarkEyeDragon** [comment]
> @DarkEyeDragon Is there anything else I can do to help you with debugging this? I am using the aikar flags already. I've started restarting my server twice a day now just to prevent it running out of ram.

First of all, making sure it's actually the plugin that causes it. Run the server without it for a while see what that does. If you can confirm it only does this when using RTP i'll look into setting up a profiler and do some testing/debugging to look further into it.

**Comment by efinst0rm** [comment]
Hey,

Alright after a month of testing I've found pregening the worlds will help reduce the ram usage. Without of pregen the ram usage would be pretty high.
