### ISSUE TITLE
Multiple World Support

### ISSUE THREAD

**Issue by Klawdek** [DarkEyeDragon/RandomTeleport#2]
It would be nice to be able to set different teleport radius and offsets in different worlds.

**Comment by DarkEyeDragon** [comment]
I'll try to do this when i got some spare time. As for right now i'm rather busy with real life stuff and other projects. Stay tuned for a later release

**Comment by DarkEyeDragon** [comment]
Adressed in: https://github.com/DarkEyeDragon/RandomTeleport/commit/b10923d805f00ea9e299d04abed2dcb8d03d9029
Will be included in the next update
