### ISSUE TITLE
Add position placeholders

### ISSUE THREAD

**Issue by xSolumx** [DarkEyeDragon/RandomTeleport#26]
**Feature Suggestion**
Add position placeholders that can be added to the teleport message

Example: 
   teleport: "&bA safe place has been found! Teleporting to %posX %posY %posZ"

=====================================================
Another cool feature would be the ability to send a title message on teleport
Example: https://prnt.sc/tdelru

**Comment by DarkEyeDragon** [comment]
I'm fine with the first part of this request. However how would you suggest doing the title bar part? How do you determine if its chat or title.

**Comment by xSolumx** [comment]
Maybe add the title bar message as a config option that can be enabled?
