### ISSUE TITLE
Disabling show-queue-population breaks the search of new safe locations

### ISSUE THREAD

**Issue by elb41** [DarkEyeDragon/RandomTeleport#275]
**Describe the bug**
If you set show-queue-population option of config to false and use the 5 safe zones loaded in the queue, it won't search for more safe zones.

**To Reproduce**
1. Set show-queue-population to false in config
2. Start the server and join
3. Spam the command /rtp 6 times to use all the safezones that the plugin load correctly
4. Use the command "/rtpdebug show queue" to see the queue list empty

**Expected behavior**
Maybe an error of code with show-queue-population option that affects to a condition method.

**Minecraft Version**
1.19.2 client
Paper 1.19.2 177 server

**Plugin version**
3.1.0 196

**Comment by DarkEyeDragon** [comment]
Fixed in build 197 and up (https://ci.darkeyedragon.me/job/Random%20Teleport/197/)
