### ISSUE TITLE
Error 1.16 Command RTP

### ISSUE THREAD

**Issue by aitechhkn** [DarkEyeDragon/RandomTeleport#29]
> INFO FrostSanta issued server command: /rtp
11.07 10:25:19 [Server] ERROR [ACF] Exception in command: rtp 
11.07 10:25:19 [Server] ERROR [ACF] java.lang.reflect.InvocationTargetException
11.07 10:25:19 [Server] ERROR [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.07 10:25:19 [Server] ERROR [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.07 10:25:19 [Server] ERROR [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.07 10:25:19 [Server] ERROR [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.acf.RegisteredCommand.invoke(RegisteredCommand.java:154)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.acf.BaseCommand.executeCommand(BaseCommand.java:577)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.acf.BaseCommand.execute(BaseCommand.java:513)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.acf.RootCommand.execute(RootCommand.java:99)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
11.07 10:25:19 [Server] ERROR [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
11.07 10:25:19 [Server] ERROR [ACF] 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
11.07 10:25:19 [Server] ERROR [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
11.07 10:25:19 [Server] ERROR [ACF] 	at java.lang.Thread.run(Thread.java:748)
11.07 10:25:19 [Server] ERROR [ACF] Caused by: java.lang.NullPointerException
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.teleport.Teleport.random(Teleport.java:105)
11.07 10:25:19 [Server] ERROR [ACF] 	at me.darkeyedragon.randomtp.command.TeleportCommand.onTeleport(TeleportCommand.java:121)
11.07 10:25:19 [Server] ERROR [ACF] 	... 27 more

**Comment by DarkEyeDragon** [comment]
What version of RTP is this?

**Comment by MisterFixx** [comment]
I hope you don't expect to get any actual help with as little information as you provided, no one here is working for you.

**Comment by DarkEyeDragon** [comment]
Seems like i managed to figure out the issue. Will be fixed in the next release
