### ISSUE TITLE
Safe Spots

### ISSUE THREAD

**Issue by MisterCookie1234** [DarkEyeDragon/RandomTeleport#30]
Lava and Water should not be considered as safe spots,
i guess?

Some players died cuz they spawned IN Water or IN Lava.

**Comment by DarkEyeDragon** [comment]
Water from rivers is considered "safe" as you should only move up a few blocks to reach the surface. 

Regarding the lava, I've had a similar report but i'm unable to reproduce it. Lava is blacklisted both in the overworld and the nether. And i was unable to spawn in lava in the 50+ attempts i've tried.
![image](https://user-images.githubusercontent.com/6131099/87857654-9f7f0d00-c928-11ea-8de2-ac16eb241fb4.png)

The only thing i could think of is that it's getting an air block with lava under it, but the Bukkit methods i use World#getHighestBlockAt does not return air blocks.

Is this overworld or nether?

**Comment by MisterCookie1234** [comment]
Well i dont mean rivers, i mean oceans. 
And players spawn deep down (maybe even within reach from drowned) and could potentially die. 

In the Nether. Happend to several users, althought its quite rare. 

I also recognized that chunks where players teleport load quite slow.
All chunks are prerendered but sometimes when u teleport it takes some times 10 seconds for the chunk to load.

**Comment by DarkEyeDragon** [comment]
Well... I honestly have no clue... Are you on 1.5.2? Also are you running Paper or Spigot?
The chunkloading has nothing to do with the plugin also, the plugin does not load or unload any chunks. The server handles that. 

I'll look deeper into it, but i dont know how to fix something i cant reproduce

**Comment by MisterCookie1234** [comment]
1.5.2 on Spigot

**Comment by botany111** [comment]
Use 1.16.1
My players will have a chance to fall into the lava after using RTP

**Comment by DarkEyeDragon** [comment]
Well i have no clue how to fix it as i dont even know how its possible to happen in the first place. I can't make it happen on my test server no matter what i try. Provide a log and config and maybe i'll be able to figure something out but i doubt it tbh.

**Comment by MisterCookie1234** [comment]
One of our players just send me this clip:
https://clips.twitch.tv/TransparentFamousSwallowDancingBaby

He spawns slightly above the Lava

**Comment by DarkEyeDragon** [comment]
Hmm. I'll look further into and try to eliminate as much edge cases as i can. But from that video i can't really pinpoint the issue. But thanks for reporting it.
