### ISSUE TITLE
Worldborder check before teleport

### ISSUE THREAD

**Issue by ShayBox** [DarkEyeDragon/RandomTeleport#32]
If `use-worldborder` is enabled, the plugin should have an additional safety check that the player isn't going to teleport outside the border, this is to protect the player from recently changed worldborder size which hast had safe spots re-calculated, I installed the plugin and it immediately teleported and killed me outside the border and continued to for some time until I'm guessing the safe spots finished calculating or something.

**Comment by DarkEyeDragon** [comment]
Currently the way you do it is by typing /rtp reload after resizing wb's. i know its not that great. I'll look into if i can make it so it reloads after wb change

**Comment by DarkEyeDragon** [comment]
So i looked a bit deeper into it and it seems its not all that simple, there is no event to listen too regarding world border changes. However i can look for the execution of the wb command

**Comment by DarkEyeDragon** [comment]
I've made an issue related to this on the paper issue tracker. https://github.com/PaperMC/Paper/issues/4720
A friend of mine is going to PR that change into paper. Once thats accepted i can start implementing a proper system for this.
As for now all we can do is play the waiting game.

**Comment by DarkEyeDragon** [comment]
If you're using one of the latest builds of paper there is a worldborder change event i hook into. 
https://ci.darkeyedragon.me/job/Random%20Teleport/98/ build 98 and up will have support for this. Do not these are dev builds and should be properly tested before using in production. Added by: https://github.com/DarkEyeDragon/RandomTeleport/pull/118/commits/7bb9baa5b05b42048371d1b473cf080605c0787e
#
