### ISSUE TITLE
Queue is empty sometimes

### ISSUE THREAD

**Issue by wysohn** [DarkEyeDragon/RandomTeleport#42]
```
10:56:53 [INFO] survival > [RandomTeleport] Safe location consumed for world (4/5)
10:57:02 [INFO] survival > [RandomTeleport] Safe location consumed for world (3/5)
10:57:15 [INFO] survival > [RandomTeleport] Safe location added for world (4/5)
```

Not sure why, but 2 safe locations are consumed, yet only 1 is filled back.

Eventually, queue is empty, and I have to reload the plugin manually to refill it.

[config.yml](https://pastebin.com/N92xPzxa)

**Comment by DarkEyeDragon** [comment]
could you provide the version and build number?

**Comment by wysohn** [comment]
Oops forgot about the important piece of information. Sorry

```
14:22:50 [INFO] survival > RandomTeleport version 1.5.0
14:22:50 [INFO] survival > Yeet a player to a random location, and hopefully they won't die in the process
14:22:50 [INFO] survival > Author: DarkEyeDragon
>version
14:22:51 [INFO] survival > This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
14:22:51 [INFO] survival > Previous version: git-Paper-133 (MC: 1.16.1)
14:22:51 [INFO] survival > You are running the latest version
```

**Comment by DarkEyeDragon** [comment]
yeah just update to the latest version this has been fixed. we're on 1.5.2 already. Either get it from https://www.spigotmc.org/resources/random-teleport.76021/ or get the latest dev builds from https://ci.darkeyedragon.me/job/Random%20Teleport/
