### ISSUE TITLE
Support for 1.12.2

### ISSUE THREAD

**Issue by Ilovemyhous** [DarkEyeDragon/RandomTeleport#43]
**Hello!**

Would is please be possible to make the plugin compatible for 1.12.2?
The plugin looks amazing and it would be nice to have it in 1.12.2.

The _issue_ is just to rename the blocks.

**Thank you in advance!** 👍 
![image](https://user-images.githubusercontent.com/50217071/90535836-99748a00-e17b-11ea-8575-3a5cc6a9afc1.png)

**Comment by Ilovemyhous** [comment]
Hey!
Sorry, for late answer?

_Is this still needed?_
I know a few servers that run 1.12.2, or even 1.8.8. And you could have more people using you'r plugin.

**Comment by DarkEyeDragon** [comment]
I dont think i'll bother then honestly.

**Comment by Ilovemyhous** [comment]
Okay, you'r plugin; you'r choice. Thank you anyway! ;)
