### ISSUE TITLE
Make it so players only see worlds in the auto fill in list that they can TP to.

### ISSUE THREAD

**Issue by Klawdek** [DarkEyeDragon/RandomTeleport#48]
**Is your feature request related to a problem? Please describe.**

When players type /rtp a list of all worlds show up even if those worlds have not even been added.

**Describe the solution you'd like**

It would be nice if that could be limited to only the worlds they are able to go to.

**Describe alternatives you've considered**

**Additional context**

**Comment by DarkEyeDragon** [comment]
Forgot to mention that i actually implemented this in the recent dev builds. https://ci.darkeyedragon.me/job/Random%20Teleport/
Note that the dev builds are 2.x and not 1.x so it is highly advised to recreate your config.yml

**Comment by Klawdek** [comment]
As of 2.0.0.68 this feature has not been added it still shows all the worlds.
