### ISSUE TITLE
Lands Plugin Support

### ISSUE THREAD

**Issue by xSorch** [DarkEyeDragon/RandomTeleport#53]
Support for Lands: https://www.spigotmc.org/resources/lands-minecraft-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-16-support.53313/ so you don't ranndom teleport into claimed areas.

**Comment by DarkEyeDragon** [comment]
I've looked into it, its not that hard to add. However, it requires my new plugin integration system to do it properly. That system is nowhere near ready for a release yet. It will be added, but only when the rewrite is finished.

**Comment by DarkEyeDragon** [comment]
Land support has been added on the dev builds. And will be available on next release.

If you want to get the build right now:
https://ci.darkeyedragon.me get the plugin from RandomTeleport (anything from build 79+ will do)
Then under addons you can find the different addons. Download whichever you want.

In the plugin folder of randomteleport add a folder "addons" (or start the server and it'll create it for you). Put the validators in there and start the server. If the server is already running you can do /rtp addon register <addon name> (it will autocomplete the name). Then you will have to reload the queue to repopulate it. (/rtp reload) then Land claims will be considered unsafe and you will no longer be rtp'd in them.
