### ISSUE TITLE
Basic API

### ISSUE THREAD

**Issue by HexedHero** [DarkEyeDragon/RandomTeleport#54]
Add a basic API such as events for when a safe location is found and when a player teleports to a safe location. Could also allow us to get the current queue of locations, an more advanced API would allow us to modify the current queue list and more but this is just basic.

**Comment by DarkEyeDragon** [comment]
Its planned for the 2.0 release. I'm rewriting part of it to support multiple platforms and add a propper api. It'll be a bit before its usuable tho.

**Comment by DarkEyeDragon** [comment]
This should be covered in https://github.com/DarkEyeDragon/RandomTeleport/pull/80. Let me know if you're missing anything else.
