### ISSUE TITLE
Lands Plugin Support

### ISSUE THREAD

**Issue by Inxity** [DarkEyeDragon/RandomTeleport#81]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Need 'Lands Claim Plugin(Premium)' for randomtp support 

**Describe alternatives you've considered**
nope

**Additional context**
https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-16-support.53313/

**Comment by DarkEyeDragon** [comment]
#53 it'll be added once i get my addon system operational. Shouldn't be too long now
