### ISSUE TITLE
Doing addworld rewrites config and delete all comments and rewrites previously made changes

### ISSUE THREAD

**Issue by Klawdek** [DarkEyeDragon/RandomTeleport#86]
**Describe the bug**
Using addworld command rewrites the entire config file.  All the documentation comments are deleted and changes made to the file are reset to defaults
**To Reproduce**
1. Look at config.  Make a change to it
2. Go in game and use the addworld command
3. Look at config and see the changes you previously made are reset and all the documentation comments have been deleted.

**Expected behavior**
I can see that since the changes made to the file were not put into memory with either a reload or restart so that may be a good explanation for that part of the problem.
However the original comments that documented the config file should not be erased.

**Screenshots**

**Minecraft Version**
What minecraft version is the server running on 1.15.2

**Plugin version**
What version of the plugin are you running?
Can be found by using `/version randomteleport`
RandomTeleport version 2.0.0.72

**Additional context**

**Comment by DarkEyeDragon** [comment]
Thats sadly just how YAML configs work. Technically comments aren't supported by the spec. So when saving the config throught the parser it removes all comments. There's nothing i can do about that.

If you make changes to the config, the plugin has no knowledge of this until you reload it. So if you make changes to the config you need to /rtp reload first so the last version of the config is in memory. And then do your changes with commands.

These are limitations by bukkit's API and YAML. I am considering alternatives, but i know people in the mc community are very familiar with YAML.

I won't close this yet as i'll see if i can find anything to solve this issue, but i make no promisses here.

**Comment by DarkEyeDragon** [comment]
Closed due to inactivity.
