### ISSUE TITLE
List only worlds that players can rtp in the list of worlds shown in rtp command

### ISSUE THREAD

**Issue by Klawdek** [DarkEyeDragon/RandomTeleport#87]
**Is your feature request related to a problem? Please describe.**
When a player types rtp the autofill shows all worlds on the server.  It would be better if it only showed the worlds that rtp has been enabled for.

**Describe the solution you'd like**
When a player types rtp a list of worlds that have been added to randomteleport config are shown and worlds that rtp cannot be used in are not listed
**Describe alternatives you've considered**

**Additional context**

I mentioned this before and it was closed saying that the feature has been added.  It has not been added.

**Comment by DarkEyeDragon** [comment]
you can get the build containing this fix here: https://ci.darkeyedragon.me/job/Random%20Teleport/73/
