### ISSUE TITLE
Menu system.

### ISSUE THREAD

**Issue by Klawdek** [DarkEyeDragon/RandomTeleport#88]
**Is your feature request related to a problem? Please describe.**
Players have to first teleport to the world they want and then they can execute the rtp command.
The autofill in the rtp command not only shows all worlds rather than just the ones they can actually teleport to there is no practical way to give instructions like do your mining in this world and build you bases in that world.

**Describe the solution you'd like**

A menu option such that when players type rtp a menu comes up.  The menu should be configurable by the admin to be able to pick the menu items and to put title and lore on menu items.
This would allow for menu items for different worlds that describe what the worlds are to be used for and any other information the player should know.

**Describe alternatives you've considered**

Some convoluted setup where players don't have permission to use rtp and another command like rt is used to open a menu with DeluxeMenus then the rtp command is executed as_server or as_op when player selects menu item.

**Additional context**

**Comment by DarkEyeDragon** [comment]
That is out of scope for the base RTP plugin.

However that being said. I am currently implementing an addon system and finalizing the api. If you can find someone to make an extension for it or even an addon system when it is done. That'd be great. 

Might make it myself in the future, but for now i have enough on my plate to keep me busy for a while.
