### ISSUE TITLE
Error log when addons folder isn't present!

### ISSUE THREAD

**Issue by Shinibami** [DarkEyeDragon/RandomTeleport#93]
**Describe the bug**
Bug is due to plugin not creating addons folder on startup

**To Reproduce**
1. Install RandomTeleport version 2.1.0.1 with new config
2. Start Server!

**Expected behavior**
Create an addons folder automatically if isn't present

**Screenshots**
https://hastebin.com/lahizituvu.properties

**Minecraft Version**
Paper version git-Paper-310 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Plugin version**
RandomTeleport version 2.1.0.1`

**Additional context**
This is my first issue report so that's all!

**Comment by DarkEyeDragon** [comment]
Fixed in https://github.com/DarkEyeDragon/RandomTeleport/commit/ec8f356fd983a2d8a08d535cfecb8bae8a8c4468

**Comment by Shinibami** [comment]
Thank you so much!
